-- MySQL Script generated by MySQL Workbench
-- 12/14/17 22:10:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rangas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rangas` (
  `rangai` VARCHAR(45) NOT NULL,
  `RangaiEN` VARCHAR(45) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asmuo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asmuo` (
  `AsmensKodas` VARCHAR(11) NOT NULL,
  `Vardas` VARCHAR(45) NOT NULL,
  `Pavarde` VARCHAR(50) NOT NULL,
  `Telefono_nr` VARCHAR(45) NOT NULL,
  `Epastas` VARCHAR(50) NOT NULL,
  `Gyvenamoji_vieta` VARCHAR(100) NOT NULL,
  `Gimimo_data` DATE NOT NULL,
  `Issilavinimas` VARCHAR(200) NULL,
  `Sveikatos_draudimas` TINYINT(1) NOT NULL,
  PRIMARY KEY (`AsmensKodas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registracija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registracija` (
  `Prisijungimo_vardas` VARCHAR(100) NOT NULL,
  `Slaptazodis` VARCHAR(200) NOT NULL,
  `Prisijungimo_klausimas` VARCHAR(100) NOT NULL,
  `Prisijungimo_atsakymas` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Prisijungimo_vardas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Darbuotojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Darbuotojas` (
  `Tabelio_nr` INT NOT NULL,
  `Dirba_nuo` DATE NOT NULL,
  `Alyginimas` DOUBLE NOT NULL,
  `Etatas` DOUBLE NOT NULL,
  `Stazas` DOUBLE NULL,
  `Rangas_id` INT NOT NULL,
  `Asmuo_AsmensKodas` VARCHAR(11) NOT NULL,
  `Registracija_Prisijungimo_vardas` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Tabelio_nr`),
  INDEX `fk_Darbuotojas_Rangas1_idx` (`Rangas_id` ASC),
  INDEX `fk_Darbuotojas_Asmuo1_idx` (`Asmuo_AsmensKodas` ASC),
  INDEX `fk_Darbuotojas_Registracija1_idx` (`Registracija_Prisijungimo_vardas` ASC),
  CONSTRAINT `fk_Darbuotojas_Rangas1`
    FOREIGN KEY (`Rangas_id`)
    REFERENCES `mydb`.`Rangas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Darbuotojas_Asmuo1`
    FOREIGN KEY (`Asmuo_AsmensKodas`)
    REFERENCES `mydb`.`Asmuo` (`AsmensKodas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Darbuotojas_Registracija1`
    FOREIGN KEY (`Registracija_Prisijungimo_vardas`)
    REFERENCES `mydb`.`Registracija` (`Prisijungimo_vardas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Padalinys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Padalinys` (
  `Inventorinis_numeris` INT NOT NULL,
  `Salis` VARCHAR(100) NOT NULL,
  `Miestas` VARCHAR(45) NOT NULL,
  `Regionas` VARCHAR(45) NULL,
  `Rajonas` VARCHAR(50) NULL,
  `Gatve` VARCHAR(100) NOT NULL,
  `padalinio_pavavadinimas` VARCHAR(100) NOT NULL,
  `SalisEN` VARCHAR(100) NULL,
  `Pasto_kodas` INT NOT NULL,
  `Ilguma` DOUBLE NOT NULL,
  `Platuma` DOUBLE NOT NULL,
  `Redaktorius` INT NOT NULL,
  PRIMARY KEY (`Inventorinis_numeris`),
  INDEX `fk_Padalinys_Darbuotojas_idx` (`Redaktorius` ASC),
  CONSTRAINT `fk_Padalinys_Darbuotojas`
    FOREIGN KEY (`Redaktorius`)
    REFERENCES `mydb`.`Darbuotojas` (`Tabelio_nr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kategorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kategorija` (
  `Kategorija_id` INT NOT NULL,
  `Kategorijos_pavadinimas` VARCHAR(50) NOT NULL,
  `KategorijaEN` VARCHAR(50) NULL,
  PRIMARY KEY (`Kategorija_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produktas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produktas` (
  `Barkodas` INT NOT NULL,
  `Pavadinimas` VARCHAR(50) NOT NULL,
  `Vieneto_kaina` DECIMAL NOT NULL,
  `Aprašymas` VARCHAR(200) NULL,
  `Matavimo_vnt` VARCHAR(45) NOT NULL,
  `Gamintojas` VARCHAR(45) NOT NULL,
  `PavadinimasEN` VARCHAR(50) NULL,
  `AprasymasEN` VARCHAR(45) NULL,
  `Pagaminimo_data` DATETIME NOT NULL,
  `Galioja_iki` DATETIME NOT NULL,
  `Tiekiama` TINYINT(1) NOT NULL,
  `Kategorija_Kategorija_id` INT NOT NULL,
  PRIMARY KEY (`Barkodas`),
  INDEX `fk_Produktas_Kategorija1_idx` (`Kategorija_Kategorija_id` ASC),
  CONSTRAINT `fk_Produktas_Kategorija1`
    FOREIGN KEY (`Kategorija_Kategorija_id`)
    REFERENCES `mydb`.`Kategorija` (`Kategorija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Padalinio_produktas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Padalinio_produktas` (
  `Kiekis` DOUBLE NOT NULL,
  `Produktas_Barkodas` INT NOT NULL,
  `Padalinys_Inventorinis_numeris` INT NOT NULL,
  PRIMARY KEY (`Produktas_Barkodas`, `Padalinys_Inventorinis_numeris`),
  INDEX `fk_Padalinio_produktas_Padalinys1_idx` (`Padalinys_Inventorinis_numeris` ASC),
  CONSTRAINT `fk_Padalinio_produktas_Produktas1`
    FOREIGN KEY (`Produktas_Barkodas`)
    REFERENCES `mydb`.`Produktas` (`Barkodas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padalinio_produktas_Padalinys1`
    FOREIGN KEY (`Padalinys_Inventorinis_numeris`)
    REFERENCES `mydb`.`Padalinys` (`Inventorinis_numeris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Busena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Busena` (
  `Busenos_id` INT NOT NULL,
  `Busenos_pavadinimas` VARCHAR(45) NOT NULL,
  `Busenos_pavEN` VARCHAR(45) NULL,
  PRIMARY KEY (`Busenos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vairuotoju_teises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vairuotoju_teises` (
  `Numeris` INT NOT NULL,
  `Galioja_nuo` DATE NOT NULL,
  `Galioja_iki` DATE NOT NULL,
  PRIMARY KEY (`Numeris`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vairuotojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vairuotojas` (
  `Tabelio_nr` INT NOT NULL,
  `Vairavimo_stazas` DOUBLE NULL,
  `Prasizengimu_sk` INT NULL,
  `Profesine_kvalifikacija` VARCHAR(100) NULL,
  `Technografo_kortele` TINYINT(1) NOT NULL,
  `Registracija_Prisijungimo_vardas` VARCHAR(100) NOT NULL,
  `Asmuo_AsmensKodas` VARCHAR(11) NOT NULL,
  `Vairuotoju_teises_Numeris` INT NOT NULL,
  PRIMARY KEY (`Tabelio_nr`),
  INDEX `fk_Vairuotojas_Registracija1_idx` (`Registracija_Prisijungimo_vardas` ASC),
  INDEX `fk_Vairuotojas_Asmuo1_idx` (`Asmuo_AsmensKodas` ASC),
  INDEX `fk_Vairuotojas_Vairuotoju_teises1_idx` (`Vairuotoju_teises_Numeris` ASC),
  CONSTRAINT `fk_Vairuotojas_Registracija1`
    FOREIGN KEY (`Registracija_Prisijungimo_vardas`)
    REFERENCES `mydb`.`Registracija` (`Prisijungimo_vardas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vairuotojas_Asmuo1`
    FOREIGN KEY (`Asmuo_AsmensKodas`)
    REFERENCES `mydb`.`Asmuo` (`AsmensKodas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vairuotojas_Vairuotoju_teises1`
    FOREIGN KEY (`Vairuotoju_teises_Numeris`)
    REFERENCES `mydb`.`Vairuotoju_teises` (`Numeris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transporto_busena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transporto_busena` (
  `Busenos_id` INT NOT NULL,
  `Busena` VARCHAR(45) NOT NULL,
  `BusenaEN` VARCHAR(45) NULL,
  PRIMARY KEY (`Busenos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vairavimo_kategorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vairavimo_kategorija` (
  `Kategorijos_id` INT NOT NULL,
  `kategorija` VARCHAR(50) NULL,
  PRIMARY KEY (`Kategorijos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transporto_priemone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transporto_priemone` (
  `Valstybinis_nr` VARCHAR(100) NOT NULL,
  `Plotis` DOUBLE NOT NULL,
  `Aukstis` DOUBLE NOT NULL,
  `Modelis` VARCHAR(50) NOT NULL,
  `Marke` VARCHAR(45) NULL,
  `Galia` DOUBLE NOT NULL,
  `Rida` INT NOT NULL,
  `Draudimas_galioja_nuo` DATE NOT NULL,
  `Draudimas_galioja_iki` DATE NOT NULL,
  `Apziura_galioja_nuo` DATE NOT NULL,
  `Apziura_galioja_iki` DATE NOT NULL,
  `Pagaminimo_metai` YEAR NOT NULL,
  `Kuro_tipas` VARCHAR(45) NOT NULL,
  `Svoris` DOUBLE NOT NULL,
  `Sedimu_vt_sk` INT NULL,
  `Variklio_darbinis_turis` DOUBLE NULL,
  `Didziausias_leidz_svoris` DOUBLE NOT NULL,
  `Spalva` VARCHAR(45) NULL,
  `Transporto_busena_Busenos_id` INT NOT NULL,
  `Vairavimo_kategorija_Kategorijos_id` INT NOT NULL,
  PRIMARY KEY (`Valstybinis_nr`),
  INDEX `fk_Transporto_priemone_Transporto_busena1_idx` (`Transporto_busena_Busenos_id` ASC),
  INDEX `fk_Transporto_priemone_Vairavimo_kategorija1_idx` (`Vairavimo_kategorija_Kategorijos_id` ASC),
  CONSTRAINT `fk_Transporto_priemone_Transporto_busena1`
    FOREIGN KEY (`Transporto_busena_Busenos_id`)
    REFERENCES `mydb`.`Transporto_busena` (`Busenos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transporto_priemone_Vairavimo_kategorija1`
    FOREIGN KEY (`Vairavimo_kategorija_Kategorijos_id`)
    REFERENCES `mydb`.`Vairavimo_kategorija` (`Kategorijos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uzsakymas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uzsakymas` (
  `Numeris` INT NOT NULL,
  `Uzsakymo_data` DATETIME NOT NULL,
  `Atlikimo_data` DATETIME NOT NULL,
  `Prioritetas` INT NOT NULL,
  `Busena` INT NOT NULL,
  `Suformavo` INT NOT NULL,
  `Vairuotojas` INT NOT NULL,
  `TransportoPriemone` VARCHAR(100) NOT NULL,
  `IsPadalinio` INT NOT NULL,
  `IPadalini` INT NOT NULL,
  PRIMARY KEY (`Numeris`),
  INDEX `fk_Uzsakymas_Busena1_idx` (`Busena` ASC),
  INDEX `fk_Uzsakymas_Darbuotojas1_idx` (`Suformavo` ASC),
  INDEX `fk_Uzsakymas_Vairuotojas1_idx` (`Vairuotojas` ASC),
  INDEX `fk_Uzsakymas_Transporto_priemone1_idx` (`TransportoPriemone` ASC),
  INDEX `fk_Uzsakymas_Padalinys1_idx` (`IsPadalinio` ASC),
  INDEX `fk_Uzsakymas_Padalinys2_idx` (`IPadalini` ASC),
  CONSTRAINT `fk_Uzsakymas_Busena1`
    FOREIGN KEY (`Busena`)
    REFERENCES `mydb`.`Busena` (`Busenos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzsakymas_Darbuotojas1`
    FOREIGN KEY (`Suformavo`)
    REFERENCES `mydb`.`Darbuotojas` (`Tabelio_nr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzsakymas_Vairuotojas1`
    FOREIGN KEY (`Vairuotojas`)
    REFERENCES `mydb`.`Vairuotojas` (`Tabelio_nr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzsakymas_Transporto_priemone1`
    FOREIGN KEY (`TransportoPriemone`)
    REFERENCES `mydb`.`Transporto_priemone` (`Valstybinis_nr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzsakymas_Padalinys1`
    FOREIGN KEY (`IsPadalinio`)
    REFERENCES `mydb`.`Padalinys` (`Inventorinis_numeris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzsakymas_Padalinys2`
    FOREIGN KEY (`IPadalini`)
    REFERENCES `mydb`.`Padalinys` (`Inventorinis_numeris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uzsakymo_produktas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uzsakymo_produktas` (
  `Kiekis` INT NOT NULL,
  `Produktas_Barkodas` INT NOT NULL,
  `Uzsakymas_Numeris` INT NOT NULL,
  PRIMARY KEY (`Produktas_Barkodas`, `Uzsakymas_Numeris`),
  INDEX `fk_Uzsakymo_produktas_Uzsakymas1_idx` (`Uzsakymas_Numeris` ASC),
  CONSTRAINT `fk_Uzsakymo_produktas_Produktas1`
    FOREIGN KEY (`Produktas_Barkodas`)
    REFERENCES `mydb`.`Produktas` (`Barkodas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzsakymo_produktas_Uzsakymas1`
    FOREIGN KEY (`Uzsakymas_Numeris`)
    REFERENCES `mydb`.`Uzsakymas` (`Numeris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DirbaPadalinyje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DirbaPadalinyje` (
  `Padalinys_Inventorinis_numeris` INT NOT NULL,
  `Darbuotojas_Tabelio_nr` INT NOT NULL,
  PRIMARY KEY (`Padalinys_Inventorinis_numeris`, `Darbuotojas_Tabelio_nr`),
  INDEX `fk_Padalinys_has_Darbuotojas_Darbuotojas1_idx` (`Darbuotojas_Tabelio_nr` ASC),
  INDEX `fk_Padalinys_has_Darbuotojas_Padalinys1_idx` (`Padalinys_Inventorinis_numeris` ASC),
  CONSTRAINT `fk_Padalinys_has_Darbuotojas_Padalinys1`
    FOREIGN KEY (`Padalinys_Inventorinis_numeris`)
    REFERENCES `mydb`.`Padalinys` (`Inventorinis_numeris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padalinys_has_Darbuotojas_Darbuotojas1`
    FOREIGN KEY (`Darbuotojas_Tabelio_nr`)
    REFERENCES `mydb`.`Darbuotojas` (`Tabelio_nr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vairuotojo_Kategorijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vairuotojo_Kategorijos` (
  `Vairuotoju_teises_Numeris` INT NOT NULL,
  `Vairavimo_kategorija_Kategorijos_id` INT NOT NULL,
  PRIMARY KEY (`Vairuotoju_teises_Numeris`, `Vairavimo_kategorija_Kategorijos_id`),
  INDEX `fk_Vairuotoju_teises_has_Vairavimo_kategorija_Vairavimo_kat_idx` (`Vairavimo_kategorija_Kategorijos_id` ASC),
  INDEX `fk_Vairuotoju_teises_has_Vairavimo_kategorija_Vairuotoju_te_idx` (`Vairuotoju_teises_Numeris` ASC),
  CONSTRAINT `fk_Vairuotoju_teises_has_Vairavimo_kategorija_Vairuotoju_teis1`
    FOREIGN KEY (`Vairuotoju_teises_Numeris`)
    REFERENCES `mydb`.`Vairuotoju_teises` (`Numeris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vairuotoju_teises_has_Vairavimo_kategorija_Vairavimo_kateg1`
    FOREIGN KEY (`Vairavimo_kategorija_Kategorijos_id`)
    REFERENCES `mydb`.`Vairavimo_kategorija` (`Kategorijos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
